version: 2.1

orbs:
  orb-tools: circleci/orb-tools@volatile
workflows:
  btd:
    jobs:
    - orb-tools/validate-orb:
        orb-path: ./.circleci/orb.yml # relative to root, not to config
        workspace-path: ./workspace/
    - orb-tools/publish-dev-orb:
        namespace: circleci
        orb-name: hello-build
        label: ${CIRCLE_BRANCH}
        dev-token-variable: "$CIRCLECI_DEV_API_TOKEN"
        workspace-path: ./workspace/
        requires: [orb-tools/validate-orb]