version: 2.1

orbs:
  clojure: hannah/clojure@dev:test

jobs:
  build:
    executor:
      name: clojure/generic_exec
      docker_image: clojure:lein-2.8.1
      wd: ~/leiningen
    steps:
      - clojure/cached_test:
          restore_key: << checksum "project.clj" >>
          pre_test_steps:
            - run:
                working_directory: ~/leiningen/leiningen-core
                command: lein bootstrap
          test_str: "bin/lein test"
          post-steps:
            - save_cache:
                paths:
                - $HOME/.m2
                - $HOME/.lein
                key: << checksum "project.clj" >>
