version: 2.1
orbs:
  inline_example:
    jobs:
      generic_job:
        parameters:
          restore_key:
              type: string
              default: "<< checksum \"project.clj\" >>"
          test_str:
              type: string
              default: "lein test"
          test_directory:
              type: string
              default: ""
          save_key:
            type: string
            default: "<< checksum \"project.clj\" >>"
          save_paths:
            type: steps
            default:
              - ~/.m2
          wd:
            type: string
            default: "~"
          docker_image:
            type: string
            default: "circleci/clojure:lein"
        executor:
          name: generic_exec
          wd: << parameters.wd >>
          docker_image: << parameters.docker_image >>
        steps:
          - checkout
          - restore_cache:
              key: << parameters.restore_key >>
          - run: << parameters.test_str >>
          - save_cache:
              key: << parameters.save_key >>
              paths: << parameters.save_paths >>
      my_inline_job:
        parameters:
          greeting_name:
            type: string
            default: olleh # is this a typo? or does this work?
        executor: my_inline_executor
        steps:
        - my_inline_command:
            name: <<parameters.greeting_name>>
    commands:
      my_inline_command:
        parameters:
          name:
            type: string
        steps:
        - run: echo "hello <<parameters.name>>, from the inline command"
    executors:
      generic_exec:
        parameters:
          wd:
            type: string
            default: foo
          docker_image:
            type: string
            default: foobar
        working_directory: << parameters.wd >>
        docker:
          - image: <<parameters.docker_image>>
      my_inline_executor:
        parameters:
          version:
            type: string
            default: "2.4"
        docker:
        - image: circleci/ruby:<<parameters.version>>

workflows:
  build-test-deploy:
    jobs:
    - inline_example/my_inline_job:
        name: build
    - inline_example/my_inline_job:
        name: build2
        greeting_name: world
